### ISSUE TITLE
Problems with pyrealsense2

### ISSUE THREAD

**Issue by densnz** [35selim/RealSense-Jetson#1]
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyrealsense2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pyrealsense2'

Your code helped me install the SDK, but pyrealsense2 could not install. Most likely the problem is in the PYTHONPATH, but it's not certain)

**Comment by aeites** [comment]
I got `pyrealsense2` to build properly but I had to manually link the library file to my python path using:

```
sudo mkdir /usr/local/lib/python3.8/pyrealsense2
sudo ln -s ~/librealsense/build/wrappers/python/pybackend2.cpython-38-aarch64-linux-gnu.so /usr/local/lib/python3.8/pyrealsense2/
sudo ln -s ~/librealsense/build/wrappers/python/pyrealsense2.cpython-38-aarch64-linux-gnu.so /usr/local/lib/python3.8/pyrealsense2/
```

After this `import pyrealsense2` should work.

**Comment by ysozkaya** [comment]
The problem was that the location of "99-realsense-libusb.rules" file is "/librealsense/config/". That is why, "build_pyrealsense2_and_SDK.sh" is updated.
