### ISSUE TITLE
realsense-viewer: command not found

### ISSUE THREAD

**Issue by DBern97** [35selim/RealSense-Jetson#2]
Hi, 

I followed your installation procedure and ran build_pyrelasense2_and_SDK.sh but the realsense-viewer command is not found.

I ran the script on Jetson Nano and th eonly thing I changed was: -DBUILD_EXAMPLES=false -DBUILD_GRAPHICAL_EXAMPLES=false.

Do you have any suggestions on how to fix this?
Thanks!

**Comment by ysozkaya** [comment]
Hi @DBern97,

If you can use pyrealsense2 without any errors, you can run `install_SDK_without_pyrealsense2.sh` to build the SDK. Since you have successfully built the python wrapper, you can just download the SDK as given in [linux distribution of librealsense](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md).
By the way, if you saw any errors while running `build_pyrelasense2_and_SDK.sh`, please share here.

Best regards,
Yavuz Selim

**Comment by DBern97** [comment]
Hi @35selim,

Thank you for such a quick reply! This is what I see in librealsense/build/CMakeFiles/CMakeError.log:

"
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/crispy/librealsense/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_ee212/fast"
/usr/bin/make -f CMakeFiles/cmTC_ee212.dir/build.make CMakeFiles/cmTC_ee212.dir/build
make[1]: Entering directory '/home/crispy/librealsense/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_ee212.dir/CheckSymbolExists.c.o
/usr/bin/cc   -fPIC  -fPIE   -o CMakeFiles/cmTC_ee212.dir/CheckSymbolExists.c.o   -c /home/crispy/librealsense/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_ee212
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_ee212.dir/link.txt --verbose=1
/usr/bin/cc -fPIC     CMakeFiles/cmTC_ee212.dir/CheckSymbolExists.c.o  -o cmTC_ee212
CMakeFiles/cmTC_ee212.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x14): undefined reference to `pthread_create'
CheckSymbolExists.c:(.text+0x18): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_ee212.dir/build.make:97: recipe for target 'cmTC_ee212' failed
make[1]: *** [cmTC_ee212] Error 1
make[1]: Leaving directory '/home/crispy/librealsense/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_ee212/fast' failed
make: *** [cmTC_ee212/fast] Error 2

File /home/crispy/librealsense/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/crispy/librealsense/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_e5cfb/fast"
/usr/bin/make -f CMakeFiles/cmTC_e5cfb.dir/build.make CMakeFiles/cmTC_e5cfb.dir/build
make[1]: Entering directory '/home/crispy/librealsense/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_e5cfb.dir/CheckFunctionExists.c.o
/usr/bin/cc   -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create -fPIE   -o CMakeFiles/cmTC_e5cfb.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.10/Modules/CheckFunctionExists.c
Linking C executable cmTC_e5cfb
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_e5cfb.dir/link.txt --verbose=1
/usr/bin/cc -fPIC -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_e5cfb.dir/CheckFunctionExists.c.o  -o cmTC_e5cfb -lpthreads
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_e5cfb.dir/build.make:97: recipe for target 'cmTC_e5cfb' failed
make[1]: *** [cmTC_e5cfb] Error 1
make[1]: Leaving directory '/home/crispy/librealsense/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_e5cfb/fast' failed
make: *** [cmTC_e5cfb/fast] Error 2
"

I will try to run the SDK installation without pyrealsense2.

Thanks!

**Comment by DBern97** [comment]
Hi @35selim,

Running the SDK only installation solved my problem. The only thing needed was to delete one of the udev-dev rules (the SDK only creates the "60-librealsense... .rules" file which is identical to the one created from the build installation).

Cheers!

**Comment by ysozkaya** [comment]
It is nice to see that your problem is solved @DBern97 !
Have a good day.

Yavuz Selim
